{% set version = "20.12.16259" %}

package:
  name: intel-compute-runtime
  version: {{ version }}

source:
  url: https://github.com/intel/compute-runtime/archive/{{ version }}.tar.gz
  sha256: cd4eb236508101c153ab7748378edcdba3fad67be9055fc5485f39718ffe8140
  patches:
    - install_icd.diff

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - intel-gmmlib
    - intel-graphics-compiler
  run:
    - {{ pin_compatible("intel-gmmlib", exact=True) }}
    - {{ pin_compatible("intel-graphics-compiler", exact=True) }}

test:
  commands:
    - test -f ${PREFIX}/lib/intel-opencl/libigdrcl${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/etc/OpenCL/vendors/intel.icd  # [unix]

about:
  home: https://github.com/intel/compute-runtime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Intel(R) Graphics Compute Runtime for OpenCL(TM)

extra:
  recipe-maintainers:
    - isuruf
