{% set version = "19.47.14903" %}

package:
  name: intel-compute-runtime
  version: {{ version }}

source:
  url: https://github.com/intel/compute-runtime/archive/{{ version }}.tar.gz
  sha256: bd15625d4e459af0b782b1ee5048d16257cf44a1f794f3c81ef07544f25c32ce
  patches:
    - add_rt.diff
    - install_icd.diff

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - intel-gmmlib
    - intel-graphics-compiler
  run:
    - {{ pin_compatible("intel-gmmlib", exact=True) }}
    - {{ pin_compatible("intel-graphics-compiler", exact=True) }}

test:
  commands:
    - test -f ${PREFIX}/lib/intel-opencl/libigdrcl${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/etc/OpenCL/vendors/intel.icd  # [unix]

about:
  home: https://github.com/intel/compute-runtime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Intel(R) Graphics Compute Runtime for OpenCL(TM)'

extra:
  recipe-maintainers:
    - isuruf
