{% set name = "intel-compute-runtime" %}
{% set version = "25.05.32567.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/intel/compute-runtime/archive/{{ version }}.tar.gz
  sha256: 6c675e9307db1358d0b97a5e227a4b051cc1495b2b43db96b3d2fc18473f4c39

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - intel-gmmlib
    # intel-graphics-compiler will be added to runtime dependency and
    #   there is no hard links to this package. However it is required for the
    #   compute runtime. Do no ignore run time dependencies from this package.
    - intel-graphics-compiler
  run:
    # TODO: remove, once merged:
    #   https://github.com/conda-forge/intel-gmmlib-feedstock/pull/38
    - {{ pin_compatible("intel-gmmlib", max_pin='x') }}

test:
  commands:
    - test -f ${PREFIX}/lib/intel-opencl/libigdrcl${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/etc/OpenCL/vendors/intel.icd  # [unix]

about:
  home: https://github.com/intel/compute-runtime
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Intel(R) Graphics Compute Runtime for OpenCL(TM)

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - isuruf
