{% set version = "26.18.38308.1" %}

package:
  name: intel-compute-runtime
  version: {{ version }}

source:
  url: https://github.com/intel/compute-runtime/archive/{{ version }}.tar.gz
  sha256: a192110226b98fc6fa640ed5f948c7b88fbed7e86536c61a4633b690a84b9792

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - intel-gmmlib
    # intel-graphics-compiler will be added to runtime dependency and
    #   there is no hard links to this package. However it is required for the
    #   compute runtime. Do no ignore run time dependencies from this package.
    - intel-graphics-compiler

test:
  commands:
    - test -f ${PREFIX}/lib/intel-opencl/libigdrcl${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/etc/OpenCL/vendors/intel.icd  # [unix]

about:
  home: https://github.com/intel/compute-runtime
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Intel(R) Graphics Compute Runtime for OpenCL(TM)

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - isuruf
