{% set name = "intel-compute-runtime" %}
{% set version = "24.35.30872.29" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/intel/compute-runtime/archive/{{ version }}.tar.gz
  sha256: cb8c4da00101d187b1669aedd43f91ebbcfc02b9d0a334d9b9221a9c8db2d5b7

build:
  number: 0
  skip: true  # [not linux]
  ignore_run_exports_from:
    # TODO: is it necessary to ignore run exports from these packages?
    #   Perhaps it is a soft dependency
    - intel-graphics-compiler
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - intel-gmmlib
    - intel-graphics-compiler
  run:
    # TODO: remove, once merged:
    #   https://github.com/conda-forge/intel-gmmlib-feedstock/pull/38
    - {{ pin_compatible("intel-gmmlib", max_pin='x') }}

test:
  commands:
    - test -f ${PREFIX}/lib/intel-opencl/libigdrcl${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/etc/OpenCL/vendors/intel.icd  # [unix]

about:
  home: https://github.com/intel/compute-runtime
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Intel(R) Graphics Compute Runtime for OpenCL(TM)

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - isuruf
